import React, { useState, useEffect } from "react";
import {
  Book,
  Calendar,
  FileText,
  Download,
  Sparkles,
  ChevronRight,
  CheckCircle,
  AlertCircle,
  Loader,
} from "lucide-react";

/**
 * PROFESSIONAL LESSON PLAN GENERATOR
 * Modern, Educational Design with Nigerian Context
 */

const LessonPlanGenerator = () => {
  // State Management
  const [step, setStep] = useState(1);
  const [formData, setFormData] = useState({
    level: "",
    subject: "",
    term: "",
    week: "",
    teacherName: "",
    schoolName: "",
    duration: "40",
  });
  const [subjects, setSubjects] = useState([]);
  const [lessonPlan, setLessonPlan] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);

  // Nigerian Education System Data
  const levels = [
    { value: "Primary 1", label: "Primary 1", color: "#FF6B6B" },
    { value: "Primary 2", label: "Primary 2", color: "#FF8C42" },
    { value: "Primary 3", label: "Primary 3", color: "#FFB84D" },
    { value: "Primary 4", label: "Primary 4", color: "#95E1D3" },
    { value: "Primary 5", label: "Primary 5", color: "#38A3A5" },
    { value: "Primary 6", label: "Primary 6", color: "#22577A" },
    { value: "JSS 1", label: "JSS 1", color: "#5D5FEF" },
    { value: "JSS 2", label: "JSS 2", color: "#7B68EE" },
    { value: "JSS 3", label: "JSS 3", color: "#9370DB" },
    { value: "SS 1", label: "SS 1", color: "#E94560" },
    { value: "SS 2", label: "SS 2", color: "#D63447" },
    { value: "SS 3", label: "SS 3", color: "#C62E65" },
  ];

  const terms = [
    { value: "First Term", label: "First Term (Sept - Dec)" },
    { value: "Second Term", label: "Second Term (Jan - April)" },
    { value: "Third Term", label: "Third Term (May - July)" },
  ];

  const weeks = Array.from({ length: 10 }, (_, i) => ({
    value: i + 1,
    label: `Week ${i + 1}`,
  }));

  // Fetch subjects when level changes
  useEffect(() => {
    if (formData.level) {
      fetchSubjects(formData.level);
    }
  }, [formData.level]);

  const fetchSubjects = async (level) => {
    try {
      const response = await fetch(
        `/api/curriculum/subjects?level=${encodeURIComponent(level)}`,
      );
      const data = await response.json();
      if (data.success) {
        setSubjects(data.subjects.map((s) => ({ value: s, label: s })));
      }
    } catch (err) {
      console.error("Error fetching subjects:", err);
    }
  };

  const handleInputChange = (field, value) => {
    setFormData((prev) => ({ ...prev, [field]: value }));
    setError(null);
  };

  const handleNext = () => {
    if (step === 1 && (!formData.level || !formData.subject)) {
      setError("Please select both level and subject");
      return;
    }
    if (step === 2 && (!formData.term || !formData.week)) {
      setError("Please select term and week");
      return;
    }
    setStep(step + 1);
    setError(null);
  };

  const handleBack = () => {
    setStep(step - 1);
    setError(null);
  };

  const generateLessonPlan = async () => {
    setLoading(true);
    setError(null);

    try {
      const response = await fetch("/api/lessons/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          level: formData.level,
          subject: formData.subject,
          term: formData.term,
          week: parseInt(formData.week),
          teacherName: formData.teacherName,
          schoolName: formData.schoolName,
          duration: formData.duration,
        }),
      });

      const data = await response.json();

      if (data.success) {
        setLessonPlan(data.lessonPlan);
        setStep(4);
      } else {
        setError(data.error || "Failed to generate lesson plan");
      }
    } catch (err) {
      setError("Network error. Please check your connection and try again.");
    } finally {
      setLoading(false);
    }
  };

  const downloadLessonPlan = () => {
    // Create downloadable document
    const content = `
LESSON PLAN
${formData.schoolName || "School Name"}

Teacher: ${formData.teacherName || "N/A"}
Class: ${formData.level}
Subject: ${formData.subject}
Term: ${formData.term}
Week: ${formData.week}
Duration: ${formData.duration} minutes

TOPIC: ${lessonPlan.topic}

CONTENT:
${lessonPlan.content}

LEARNING OBJECTIVES:
${lessonPlan.objectives?.map((obj, i) => `${i + 1}. ${obj}`).join("\n") || "N/A"}

TEACHING AIDS:
${lessonPlan.teachingAids?.join(", ") || "N/A"}

ACTIVITIES:
${lessonPlan.activities?.map((act, i) => `${i + 1}. ${act}`).join("\n") || "N/A"}

ASSESSMENT:
${lessonPlan.assessment || "N/A"}

Generated by Curriculum Box - ${new Date().toLocaleDateString()}
    `;

    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `LessonPlan_${formData.subject}_Week${formData.week}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const resetForm = () => {
    setStep(1);
    setFormData({
      level: "",
      subject: "",
      term: "",
      week: "",
      teacherName: "",
      schoolName: "",
      duration: "40",
    });
    setLessonPlan(null);
    setError(null);
  };

  return (
    <div style={styles.container}>
      <header style={styles.header}>
        <div style={styles.headerContent}>
          <div style={styles.logoSection}>
            <div style={styles.logoIcon}>
              <Book size={28} />
            </div>
            <div>
              <h1 style={styles.logoText}>Curriculum Box</h1>
              <p style={styles.logoSubtext}>Professional Educator Suite</p>
            </div>
          </div>
          <div style={styles.badge}>
            <CheckCircle size={16} />
            <span>NERDC Compliant</span>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main style={styles.main}>
        <div style={styles.content}>
          {/* Progress Steps */}
          <div className="glass-panel" style={styles.progressContainer}>
            {[
              { num: 1, label: "Class & Subject", icon: Book },
              { num: 2, label: "Term & Week", icon: Calendar },
              { num: 3, label: "Details", icon: FileText },
              { num: 4, label: "Generated", icon: CheckCircle },
            ].map((item, index) => (
              <React.Fragment key={item.num}>
                <div
                  style={{
                    ...styles.progressStep,
                    ...(step >= item.num ? styles.progressStepActive : {}),
                  }}
                >
                  <div
                    style={{
                      ...styles.progressCircle,
                      ...(step >= item.num ? styles.progressCircleActive : {}),
                      ...(step > item.num ? styles.progressCircleComplete : {}),
                    }}
                  >
                    {step > item.num ? (
                      <CheckCircle size={20} />
                    ) : (
                      <item.icon size={20} />
                    )}
                  </div>
                  <span style={styles.progressLabel}>{item.label}</span>
                </div>
                {index < 3 && (
                  <div
                    style={{
                      ...styles.progressLine,
                      ...(step > item.num ? styles.progressLineActive : {}),
                    }}
                  />
                )}
              </React.Fragment>
            ))}
          </div>

          {/* Form Card */}
          <div style={styles.card}>
            {/* Step 1: Level & Subject */}
            {step === 1 && (
              <div style={styles.stepContent}>
                <h2 style={styles.stepTitle}>Select Class Level & Subject</h2>
                <p style={styles.stepDescription}>
                  Choose the class level and subject for your lesson plan
                </p>

                <div style={styles.formGroup}>
                  <label style={styles.label}>Class Level *</label>
                  <div style={styles.gridContainer}>
                    {levels.map((level) => (
                      <button
                        key={level.value}
                        onClick={() => handleInputChange("level", level.value)}
                        style={{
                          ...styles.selectCard,
                          ...(formData.level === level.value
                            ? {
                                ...styles.selectCardActive,
                                borderColor: level.color,
                                background: `${level.color}15`,
                              }
                            : {}),
                        }}
                      >
                        <div
                          style={{
                            ...styles.selectCardDot,
                            background: level.color,
                          }}
                        />
                        <span style={styles.selectCardLabel}>
                          {level.label}
                        </span>
                        {formData.level === level.value && (
                          <CheckCircle
                            size={18}
                            style={{ color: level.color }}
                          />
                        )}
                      </button>
                    ))}
                  </div>
                </div>

                {formData.level && (
                  <div style={styles.formGroup}>
                    <label style={styles.label}>Subject *</label>
                    <select
                      value={formData.subject}
                      onChange={(e) =>
                        handleInputChange("subject", e.target.value)
                      }
                      style={styles.select}
                    >
                      <option value="">Select subject...</option>
                      {subjects.map((subject) => (
                        <option key={subject.value} value={subject.value}>
                          {subject.label}
                        </option>
                      ))}
                    </select>
                  </div>
                )}

                {error && (
                  <div style={styles.errorBox}>
                    <AlertCircle size={18} />
                    <span>{error}</span>
                  </div>
                )}

                <button
                  onClick={handleNext}
                  style={styles.primaryButton}
                  disabled={!formData.level || !formData.subject}
                >
                  Continue
                  <ChevronRight size={20} />
                </button>
              </div>
            )}

            {/* Step 2: Term & Week */}
            {step === 2 && (
              <div style={styles.stepContent}>
                <h2 style={styles.stepTitle}>Select Term & Week</h2>
                <p style={styles.stepDescription}>
                  Choose the academic term and week number
                </p>

                <div style={styles.formGroup}>
                  <label style={styles.label}>Academic Term *</label>
                  <div style={styles.termGrid}>
                    {terms.map((term) => (
                      <button
                        key={term.value}
                        onClick={() => handleInputChange("term", term.value)}
                        style={{
                          ...styles.termCard,
                          ...(formData.term === term.value
                            ? styles.termCardActive
                            : {}),
                        }}
                      >
                        <Calendar size={24} />
                        <div>
                          <div style={styles.termCardTitle}>
                            {term.label.split("(")[0]}
                          </div>
                          <div style={styles.termCardSubtitle}>
                            {term.label.match(/\((.*?)\)/)?.[1]}
                          </div>
                        </div>
                        {formData.term === term.value && (
                          <CheckCircle
                            size={20}
                            style={{ marginLeft: "auto" }}
                          />
                        )}
                      </button>
                    ))}
                  </div>
                </div>

                {formData.term && (
                  <div style={styles.formGroup}>
                    <label style={styles.label}>Week Number *</label>
                    <div style={styles.weekGrid}>
                      {weeks.map((week) => (
                        <button
                          key={week.value}
                          onClick={() =>
                            handleInputChange("week", week.value.toString())
                          }
                          style={{
                            ...styles.weekButton,
                            ...(formData.week === week.value.toString()
                              ? styles.weekButtonActive
                              : {}),
                          }}
                        >
                          {week.value}
                        </button>
                      ))}
                    </div>
                  </div>
                )}

                {error && (
                  <div style={styles.errorBox}>
                    <AlertCircle size={18} />
                    <span>{error}</span>
                  </div>
                )}

                <div style={styles.buttonGroup}>
                  <button onClick={handleBack} style={styles.secondaryButton}>
                    Back
                  </button>
                  <button
                    onClick={handleNext}
                    style={styles.primaryButton}
                    disabled={!formData.term || !formData.week}
                  >
                    Continue
                    <ChevronRight size={20} />
                  </button>
                </div>
              </div>
            )}

            {/* Step 3: Additional Details */}
            {step === 3 && (
              <div style={styles.stepContent}>
                <h2 style={styles.stepTitle}>Additional Details</h2>
                <p style={styles.stepDescription}>
                  Optional information to personalize your lesson plan
                </p>

                <div style={styles.formGroup}>
                  <label style={styles.label}>Teacher Name</label>
                  <input
                    type="text"
                    value={formData.teacherName}
                    onChange={(e) =>
                      handleInputChange("teacherName", e.target.value)
                    }
                    placeholder="Enter your name"
                    style={styles.input}
                  />
                </div>

                <div style={styles.formGroup}>
                  <label style={styles.label}>School Name</label>
                  <input
                    type="text"
                    value={formData.schoolName}
                    onChange={(e) =>
                      handleInputChange("schoolName", e.target.value)
                    }
                    placeholder="Enter school name"
                    style={styles.input}
                  />
                </div>

                <div style={styles.formGroup}>
                  <label style={styles.label}>Lesson Duration (minutes)</label>
                  <select
                    value={formData.duration}
                    onChange={(e) =>
                      handleInputChange("duration", e.target.value)
                    }
                    style={styles.select}
                  >
                    <option value="35">35 minutes</option>
                    <option value="40">40 minutes</option>
                    <option value="45">45 minutes</option>
                    <option value="60">60 minutes</option>
                  </select>
                </div>

                <div style={styles.summaryBox}>
                  <h3 style={styles.summaryTitle}>Lesson Plan Summary</h3>
                  <div style={styles.summaryGrid}>
                    <div style={styles.summaryItem}>
                      <span style={styles.summaryLabel}>Level:</span>
                      <span style={styles.summaryValue}>{formData.level}</span>
                    </div>
                    <div style={styles.summaryItem}>
                      <span style={styles.summaryLabel}>Subject:</span>
                      <span style={styles.summaryValue}>
                        {formData.subject}
                      </span>
                    </div>
                    <div style={styles.summaryItem}>
                      <span style={styles.summaryLabel}>Term:</span>
                      <span style={styles.summaryValue}>{formData.term}</span>
                    </div>
                    <div style={styles.summaryItem}>
                      <span style={styles.summaryLabel}>Week:</span>
                      <span style={styles.summaryValue}>
                        Week {formData.week}
                      </span>
                    </div>
                  </div>
                </div>

                {error && (
                  <div style={styles.errorBox}>
                    <AlertCircle size={18} />
                    <span>{error}</span>
                  </div>
                )}

                <div style={styles.buttonGroup}>
                  <button onClick={handleBack} style={styles.secondaryButton}>
                    Back
                  </button>
                  <button
                    onClick={generateLessonPlan}
                    style={styles.generateButton}
                    disabled={loading}
                  >
                    {loading ? (
                      <>
                        <Loader size={20} className="spin" />
                        Generating...
                      </>
                    ) : (
                      <>
                        <Sparkles size={20} />
                        Generate Lesson Plan
                      </>
                    )}
                  </button>
                </div>
              </div>
            )}

            {/* Step 4: Generated Lesson Plan */}
            {step === 4 && lessonPlan && (
              <div style={styles.stepContent}>
                <div style={styles.successBanner}>
                  <CheckCircle size={24} />
                  <div>
                    <h3 style={styles.successTitle}>Lesson Plan Generated!</h3>
                    <p style={styles.successSubtitle}>
                      Your NERDC-compliant lesson plan is ready
                    </p>
                  </div>
                </div>

                <div style={styles.lessonPlanContainer}>
                  {/* Header Info */}
                  <div style={styles.lessonHeader}>
                    <h2 style={styles.lessonTitle}>{lessonPlan.topic}</h2>
                    <div style={styles.lessonMeta}>
                      <span>{formData.level}</span>
                      <span>•</span>
                      <span>{formData.subject}</span>
                      <span>•</span>
                      <span>
                        {formData.term}, Week {formData.week}
                      </span>
                    </div>
                  </div>

                  {/* Content Sections */}
                  <div style={styles.lessonSection}>
                    <h3 style={styles.sectionTitle}>Content Summary</h3>
                    <p style={styles.sectionContent}>{lessonPlan.content}</p>
                  </div>

                  {lessonPlan.objectives &&
                    lessonPlan.objectives.length > 0 && (
                      <div style={styles.lessonSection}>
                        <h3 style={styles.sectionTitle}>Learning Objectives</h3>
                        <ul style={styles.list}>
                          {lessonPlan.objectives.map((obj, index) => (
                            <li key={index} style={styles.listItem}>
                              {obj}
                            </li>
                          ))}
                        </ul>
                      </div>
                    )}

                  {lessonPlan.teachingAids &&
                    lessonPlan.teachingAids.length > 0 && (
                      <div style={styles.lessonSection}>
                        <h3 style={styles.sectionTitle}>
                          Teaching Aids & Resources
                        </h3>
                        <div style={styles.tagContainer}>
                          {lessonPlan.teachingAids.map((aid, index) => (
                            <span key={index} style={styles.tag}>
                              {aid}
                            </span>
                          ))}
                        </div>
                      </div>
                    )}

                  {lessonPlan.activities &&
                    lessonPlan.activities.length > 0 && (
                      <div style={styles.lessonSection}>
                        <h3 style={styles.sectionTitle}>
                          Suggested Activities
                        </h3>
                        <ul style={styles.list}>
                          {lessonPlan.activities.map((activity, index) => (
                            <li key={index} style={styles.listItem}>
                              {activity}
                            </li>
                          ))}
                        </ul>
                      </div>
                    )}

                  {lessonPlan.assessment && (
                    <div style={styles.lessonSection}>
                      <h3 style={styles.sectionTitle}>Assessment</h3>
                      <p style={styles.sectionContent}>
                        {lessonPlan.assessment}
                      </p>
                    </div>
                  )}
                </div>

                <div style={styles.buttonGroup}>
                  <button
                    onClick={downloadLessonPlan}
                    style={styles.downloadButton}
                  >
                    <Download size={20} />
                    Download
                  </button>
                  <button onClick={resetForm} style={styles.primaryButton}>
                    Create Another
                  </button>
                </div>
              </div>
            )}
          </div>
        </div>
      </main>

      {/* Footer */}
      <footer style={styles.footer}>
        <p style={styles.footerText}>
          © 2026 Curriculum Box • NERDC-Compliant Lesson Plans for Nigerian
          Schools
        </p>
      </footer>

      {/* Animations */}
      <style>{`
        .spin {
          animation: spin 1s linear infinite;
        }
        
        @keyframes spin {
          from { transform: rotate(0deg); }
          to { transform: rotate(360deg); }
        }

        @keyframes fadeIn {
          from { opacity: 0; transform: translateY(10px); }
          to { opacity: 1; transform: translateY(0); }
        }

        @keyframes slideIn {
          from { opacity: 0; transform: translateX(-20px); }
          to { opacity: 1; transform: translateX(0); }
        }
      `}</style>
    </div>
  );
};

// Comprehensive Styles
const styles = {
  container: {
    minHeight: "100vh",
    background: "linear-gradient(135deg, #043306 0%, #b5b5ab 100%)",
    fontFamily:
      "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
  },

  header: {
    background: "rgba(255, 255, 255, 0.98)",
    backdropFilter: "blur(10px)",
    borderBottom: "1px solid rgba(0, 0, 0, 0.08)",
    padding: "1.5rem 2rem",
    position: "sticky",
    top: 0,
    zIndex: 100,
    boxShadow: "0 2px 20px rgba(0, 0, 0, 0.06)",
  },

  headerContent: {
    maxWidth: "1200px",
    margin: "0 auto",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },

  logoSection: {
    display: "flex",
    alignItems: "center",
    gap: "1rem",
  },

  logoIcon: {
    width: "48px",
    height: "48px",
    background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    borderRadius: "12px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "white",
  },

  logoText: {
    fontSize: "1.5rem",
    fontWeight: "700",
    background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
    margin: 0,
  },

  logoSubtext: {
    fontSize: "0.875rem",
    color: "#64748b",
    margin: 0,
  },

  badge: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
    background: "#f0fdf4",
    color: "#166534",
    padding: "0.5rem 1rem",
    borderRadius: "999px",
    fontSize: "0.875rem",
    fontWeight: "600",
    border: "1px solid #bbf7d0",
  },

  main: {
    padding: "3rem 2rem",
  },

  content: {
    maxWidth: "900px",
    margin: "0 auto",
  },

  progressContainer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: "3rem",
    background: "rgba(255, 255, 255, 0.95)",
    padding: "2rem",
    borderRadius: "16px",
    boxShadow: "0 4px 20px rgba(0, 0, 0, 0.08)",
  },

  progressStep: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "0.75rem",
    flex: 1,
  },

  progressCircle: {
    width: "56px",
    height: "56px",
    borderRadius: "50%",
    background: "#f1f5f9",
    border: "3px solid #e2e8f0",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#94a3b8",
    transition: "all 0.3s ease",
  },

  progressCircleActive: {
    background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    borderColor: "#667eea",
    color: "white",
    transform: "scale(1.1)",
  },

  progressCircleComplete: {
    background: "#10b981",
    borderColor: "#10b981",
  },

  progressLabel: {
    fontSize: "0.875rem",
    fontWeight: "600",
    color: "#64748b",
    textAlign: "center",
  },

  progressLine: {
    height: "3px",
    flex: 1,
    background: "#e2e8f0",
    margin: "0 -1rem",
    marginTop: "-1.5rem",
    transition: "all 0.3s ease",
  },

  progressLineActive: {
    background: "linear-gradient(90deg, #667eea 0%, #764ba2 100%)",
  },

  card: {
    background: "white",
    borderRadius: "20px",
    padding: "3rem",
    boxShadow: "0 10px 40px rgba(0, 0, 0, 0.1)",
    animation: "fadeIn 0.4s ease",
  },

  stepContent: {
    animation: "slideIn 0.3s ease",
  },

  stepTitle: {
    fontSize: "2rem",
    fontWeight: "700",
    color: "#1e293b",
    marginBottom: "0.5rem",
  },

  stepDescription: {
    fontSize: "1rem",
    color: "#64748b",
    marginBottom: "2.5rem",
  },

  formGroup: {
    marginBottom: "2rem",
  },

  label: {
    display: "block",
    fontSize: "0.875rem",
    fontWeight: "600",
    color: "#334155",
    marginBottom: "0.75rem",
    textTransform: "uppercase",
    letterSpacing: "0.05em",
  },

  gridContainer: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(140px, 1fr))",
    gap: "1rem",
  },

  selectCard: {
    padding: "1.25rem",
    border: "2px solid #e2e8f0",
    borderRadius: "12px",
    background: "white",
    cursor: "pointer",
    transition: "all 0.2s ease",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "0.5rem",
    position: "relative",
  },

  selectCardActive: {
    borderWidth: "2px",
    transform: "translateY(-2px)",
    boxShadow: "0 4px 12px rgba(102, 126, 234, 0.2)",
  },

  selectCardDot: {
    width: "12px",
    height: "12px",
    borderRadius: "50%",
  },

  selectCardLabel: {
    fontSize: "0.95rem",
    fontWeight: "600",
    color: "#334155",
  },

  select: {
    width: "100%",
    padding: "0.875rem 1rem",
    border: "2px solid #e2e8f0",
    borderRadius: "10px",
    fontSize: "1rem",
    background: "white",
    cursor: "pointer",
    transition: "all 0.2s ease",
    outline: "none",
  },

  input: {
    width: "100%",
    padding: "0.875rem 1rem",
    border: "2px solid #e2e8f0",
    borderRadius: "10px",
    fontSize: "1rem",
    outline: "none",
    transition: "all 0.2s ease",
  },

  termGrid: {
    display: "grid",
    gap: "1rem",
  },

  termCard: {
    display: "flex",
    alignItems: "center",
    gap: "1rem",
    padding: "1.5rem",
    border: "2px solid #e2e8f0",
    borderRadius: "12px",
    background: "white",
    cursor: "pointer",
    transition: "all 0.2s ease",
    textAlign: "left",
  },

  termCardActive: {
    borderColor: "#667eea",
    background: "#f0f4ff",
    transform: "translateX(4px)",
  },

  termCardTitle: {
    fontSize: "1.1rem",
    fontWeight: "600",
    color: "#1e293b",
  },

  termCardSubtitle: {
    fontSize: "0.875rem",
    color: "#64748b",
    marginTop: "0.25rem",
  },

  weekGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(5, 1fr)",
    gap: "1rem",
  },

  weekButton: {
    padding: "1rem",
    border: "2px solid #e2e8f0",
    borderRadius: "10px",
    background: "white",
    fontSize: "1.1rem",
    fontWeight: "600",
    cursor: "pointer",
    transition: "all 0.2s ease",
  },

  weekButtonActive: {
    borderColor: "#667eea",
    background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    color: "white",
    transform: "scale(1.05)",
  },

  summaryBox: {
    background: "#f8fafc",
    border: "2px solid #e2e8f0",
    borderRadius: "12px",
    padding: "1.5rem",
    marginBottom: "2rem",
  },

  summaryTitle: {
    fontSize: "1rem",
    fontWeight: "600",
    color: "#334155",
    marginBottom: "1rem",
  },

  summaryGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, 1fr)",
    gap: "1rem",
  },

  summaryItem: {
    display: "flex",
    flexDirection: "column",
    gap: "0.25rem",
  },

  summaryLabel: {
    fontSize: "0.75rem",
    color: "#64748b",
    textTransform: "uppercase",
    letterSpacing: "0.05em",
  },

  summaryValue: {
    fontSize: "1rem",
    fontWeight: "600",
    color: "#1e293b",
  },

  buttonGroup: {
    display: "flex",
    gap: "1rem",
    marginTop: "2rem",
  },

  primaryButton: {
    flex: 1,
    padding: "1rem 2rem",
    background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    color: "white",
    border: "none",
    borderRadius: "10px",
    fontSize: "1rem",
    fontWeight: "600",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "0.5rem",
    transition: "all 0.2s ease",
    boxShadow: "0 4px 12px rgba(102, 126, 234, 0.3)",
  },

  secondaryButton: {
    flex: 1,
    padding: "1rem 2rem",
    background: "white",
    color: "#334155",
    border: "2px solid #e2e8f0",
    borderRadius: "10px",
    fontSize: "1rem",
    fontWeight: "600",
    cursor: "pointer",
    transition: "all 0.2s ease",
  },

  generateButton: {
    flex: 1,
    padding: "1rem 2rem",
    background: "linear-gradient(135deg, #10b981 0%, #059669 100%)",
    color: "white",
    border: "none",
    borderRadius: "10px",
    fontSize: "1rem",
    fontWeight: "600",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "0.5rem",
    transition: "all 0.2s ease",
    boxShadow: "0 4px 12px rgba(16, 185, 129, 0.3)",
  },

  downloadButton: {
    flex: 1,
    padding: "1rem 2rem",
    background: "white",
    color: "#334155",
    border: "2px solid #e2e8f0",
    borderRadius: "10px",
    fontSize: "1rem",
    fontWeight: "600",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "0.5rem",
    transition: "all 0.2s ease",
  },

  errorBox: {
    display: "flex",
    alignItems: "center",
    gap: "0.75rem",
    padding: "1rem",
    background: "#fef2f2",
    border: "1px solid #fecaca",
    borderRadius: "10px",
    color: "#991b1b",
    fontSize: "0.875rem",
    marginBottom: "1rem",
  },

  successBanner: {
    display: "flex",
    alignItems: "center",
    gap: "1rem",
    padding: "1.5rem",
    background: "#f0fdf4",
    border: "2px solid #bbf7d0",
    borderRadius: "12px",
    marginBottom: "2rem",
  },

  successTitle: {
    fontSize: "1.25rem",
    fontWeight: "700",
    color: "#166534",
    margin: 0,
  },

  successSubtitle: {
    fontSize: "0.875rem",
    color: "#15803d",
    margin: 0,
  },

  lessonPlanContainer: {
    marginBottom: "2rem",
  },

  lessonHeader: {
    marginBottom: "2rem",
    paddingBottom: "2rem",
    borderBottom: "2px solid #e2e8f0",
  },

  lessonTitle: {
    fontSize: "2rem",
    fontWeight: "700",
    color: "#1e293b",
    marginBottom: "0.75rem",
  },

  lessonMeta: {
    display: "flex",
    alignItems: "center",
    gap: "0.75rem",
    fontSize: "0.95rem",
    color: "#64748b",
  },

  lessonSection: {
    marginBottom: "2rem",
  },

  sectionTitle: {
    fontSize: "1.25rem",
    fontWeight: "600",
    color: "#334155",
    marginBottom: "1rem",
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
  },

  sectionContent: {
    fontSize: "1rem",
    color: "#475569",
    lineHeight: "1.7",
  },

  list: {
    listStyle: "none",
    padding: 0,
    margin: 0,
  },

  listItem: {
    padding: "0.75rem 0",
    paddingLeft: "1.5rem",
    position: "relative",
    fontSize: "1rem",
    color: "#475569",
    lineHeight: "1.6",
    borderBottom: "1px solid #f1f5f9",
  },

  tagContainer: {
    display: "flex",
    flexWrap: "wrap",
    gap: "0.5rem",
  },

  tag: {
    padding: "0.5rem 1rem",
    background: "#f1f5f9",
    color: "#475569",
    borderRadius: "999px",
    fontSize: "0.875rem",
    fontWeight: "500",
  },

  footer: {
    background: "rgba(255, 255, 255, 0.95)",
    borderTop: "1px solid rgba(0, 0, 0, 0.08)",
    padding: "2rem",
    textAlign: "center",
  },

  footerText: {
    color: "#64748b",
    fontSize: "0.875rem",
    margin: 0,
  },
};

export default LessonPlanGenerator;
